### PR TITLE
Removed duplicate from Ubuntu1804-README.md

### PR DESCRIPTION
**Pull request by kmadof**
I'm not 100% sure whether it is duplicate or there is multiple docker client installed side by side and it it wrong version.

### CODE REVIEW

**Comment by miketimofeev** [comment]
@kmadof thanks for reporting this. Readme is being created automatically during image generation, so we should find the root cause there, no need to fix the readme file itself.

**Comment by miketimofeev** [comment]
Looks like these 2 scripts provide the same output
https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1604.json#L130#L131

**Comment by kmadof** [comment]
@miketimofeev I see your point. I see two possible causes:

- one script is not needed
- one script should not edit docker image

Am I right?

**Comment by kmadof** [comment]
@miketimofeev I see your point. I see two possible causes:

- one script is not needed
- one script should not change README.md

Am I right?

**Comment by miketimofeev** [comment]
@kmadof looks so.
@alepauly it seems that docker.sh script extends docker-moby.sh and I'm a bit confused why do we need both of them?

**Comment by alepauly** [comment]
> @alepauly it seems that docker.sh script extends docker-moby.sh and I'm a bit confused why do we need both of them?

@ds-ms made those changes originally- and he probably knows best. Deepak, can you helps here? thanks.

**Comment by ds-ms** [comment]
Earlier when I made that change only one of those scripts was used in the packer template. 
But, from the looks of it, it seems to be a duplicate entry.

We can merge the scripts into one, `docker.sh` is being used for caching some images during the vm image generation, and `docker-moby.sh` does only `moby` install.

**Comment by kmadof** [comment]
Do you think that this PR is good place to solve that issue or maybe sth more accurate is needed?

**Comment by ds-ms** [comment]
This seems like the right place to me, given that the root cause of the problem is duplicate scripts.
Thoughts?

**Comment by al-cheb** [comment]
Hello, @kmadof 
Please don't update autogenerated documentation file. Duplicated and will be fixed in https://github.com/actions/virtual-environments/pull/470 PR.

**Pull request closed without merging**
