### PR TITLE
Add support for PHP 7.4

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by danielroe** [comment]
Looking forward to this landing - this is currently blocking our adoption of PHP 7.4 specific features.

**Comment by oldskool** [comment]
> this is currently blocking our adoption of PHP 7.4 specific features.

In the meantime you should be able to just install it manually:

```
steps:
      - name: Install PHP 7.4
        run: sudo apt-get install -y php7.4-cli
```

This will give you a PHP 7.4 installation in your workflow. Any additional extensions you'd need can be added in the same way `sudo apt-get install -y php7.4-<ext>`.

**Comment by Lctrs** [comment]
Instead of `apt-get`, you can use `apt-fast` which will speed up the installation of the packages.

Or you can use [shivammathur/setup-php](https://github.com/shivammathur/setup-php).

**Comment by danielroe** [comment]
I'm aware of both options. It's just tedious to manually specify all the specific required extensions, and I'm reluctant to spend the time when this PR is ready to go.

**Comment by zoispag** [comment]
Any luck on deploying this?

**Comment by danielroe** [comment]
@zoispag It's live.

**Comment by zoispag** [comment]
@danielroe indeed! I ran a build and it's there! Thanks :)

**Pull request merged**
