### PR TITLE
[Windows] Add Microsoft Reporting Services Projects support

### PR DESCRIPTION
**Pull request by zoran-bjelica**
# Description
Add Microsoft Reporting Services to Windows 2022 image

#### Related issue:
https://github.com/actions/virtual-environments/issues/5340

## Check list
- [x] Related issue / work item is attached
- [x] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by pavelpikatamcs** [comment]
Hi. I tried implementing this myself in a fork, but simply adding the vsix in the toolset list will not work - the marketplace page doesn't contain necessary details for the installation PowerShell script to work (like filename).

**Comment by al-cheb** [comment]
> Hi. I tried implementing this myself in a fork, but simply adding the vsix in the toolset list will not work - the marketplace page doesn't contain necessary details for the installation PowerShell script to work (like filename). I think Install-VsixExtension and Get-VsixExtenstionFromMarketplace functions will need to be adjusted for that

We will check how to fix it.

**Review by Marshinshipstat — APPROVED** [review]

**Comment by pavelpikatamcs** [comment]
Hi @al-cheb 
Are they any news about this?

**Comment by al-cheb** [comment]
> Hi @al-cheb Are they any news about this?

Currently, no updates.

**Pull request closed without merging**
