### PR TITLE
refactor: auto format JSON using VSC

### PR DESCRIPTION
**Pull request by hutson**
# Description

Reformat JSON Packer files using the default JSON formatter baked into Visual Studio Code.

Allows taking advantage of automatic JSON formatting to ensure consistent formatting across all JSON files, allowing me to focus on features instead.

#### Related issue:

None

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by maxim-lobanov** [comment]
@hutson , thank you for contribution!

I like this PR but I worry that templates' styling will be broken again in future because we have a lot of contributions.
@alepauly @AlenaSviridenko what do you think about configuring some linter for json templates? I think we can use official GH linter tool: https://github.com/github/super-linter

**Comment by AlenaSviridenko** [comment]
@maxim-lobanov I am supporting this idea for templates, but probably not for the main code as it will bring a lot of noise that may spread our focus from the code to formatting issues.

**Comment by hutson** [comment]
> I like this PR but I worry that templates' styling will be broken again in future because we have a lot of contributions.

Agreed! 👍 

> @alepauly @AlenaSviridenko what do you think about configuring some linter for json templates? I think we can use official GH linter tool: https://github.com/github/super-linter

Ideally I would like to see this integrated into Packer itself. For example, I wish `packer validate` supported plugins that we could use to integrate a _linter_ plugin into the command. We could then use `packer validate` to verify the template matched the project's preferred format. Unfortunately `packer` [only supports plugins](https://www.packer.io/docs/extending/plugins#installing-plugins) for `builder`, `post-processor`, and `provisioner`.

**Review by alepauly — APPROVED** [review]
@hutson - thank you!

**Comment by alepauly** [comment]
@maxim-lobanov - I agree with @AlenaSviridenko  - just the templates to keep them readable for now. If we want to enforce formatting in the scripts, then I would say we do it through code reviews.

**Review by maxim-lobanov — APPROVED** [review]

**Comment by maxim-lobanov** [comment]
Resolved conflict and rerun builds

**Pull request merged**
