### PR TITLE
Add CMake 3.18 in Android SDK components to toolsets (win/linux).

### PR DESCRIPTION
**Pull request by atsushieno**
# Description

This adds CMake 3.18.1 from Android SDK. The relevant information is at issue #2228.

#### Related issue:

https://github.com/actions/virtual-environments/issues/2228

### CODE REVIEW

**Review by maxim-lobanov — APPROVED** [review]

**Comment by al-cheb** [comment]
@atsushieno, All images failed with the exception -  ` Warning: Failed to find package cmake;3.18.1. Could you please check a package name?

**Comment by atsushieno** [comment]
According to view-source:file:///tmp/mozilla_atsushi0/repository2-1.xml the version ID is correct, but since it requires android-sdk-preview-license, it is likely failing your image builder internals.

Since the build failure message has almost no information, I have no further clue at the moment. Is there any way I can try to run the image builders locally?

**Comment by al-cheb** [comment]
> According to view-source:file:///tmp/mozilla_atsushi0/repository2-1.xml the version ID is correct, but since it requires android-sdk-preview-license, it is likely failing your image builder internals.
> 
> Since the build failure message has almost no information, I have no further clue at the moment. Is there any way I can try to run the image builders locally?

I think you can test installation via GitHub Actions.

**Comment by atsushieno** [comment]
Okay, now I read through the docs. Looks like I need my own azure account subscription to build images either from local console or actions anyways...

**Comment by atsushieno** [comment]
Sorry I dump the idea, I don't want to expense by building potentially huge ARM image just to investigate the problem (I have almost zero knowledge on them). That should not be my business. I stick to things that I can contribute without paying.

**Comment by miketimofeev** [comment]
@atsushieno it looks like the package is available as a preview only. We only install packages from the stable channel.

**Comment by atsushieno** [comment]
> We only install packages from the stable channel.

Fair enough.

**Comment by maxim-lobanov** [comment]
I am closing this PR for now since as @miketimofeev mentioned we use only stable channel on images. Please consider installing cmake 3.18 from preview channel in runtime.
As soon as it will be added to stable channel, we will be happy to accept this contribution.

**Comment by atsushieno** [comment]
I think you are misunderstanding the actual consequence that this problem leads to.

> Please consider installing cmake 3.18 from preview channel in runtime.

Unfortunately it does not work, as GitHub Actions setup (that it installs Android SDK under /usr/local) leads to no writable permission error. It is just that GitHub Actions won't be usable for any Android applications that depends on native code and uses Android Gradle Plugin 7.0.0. There is another workaround for the issue though.

**Comment by maxim-lobanov** [comment]
I have double checked and currently `cmake 3.18` is available only in canary channel (`sdkmanager --list --channel=3`).
I don't have much experience with Android development but not sure that it is expected that some software / libraries / plugins depend on non-stable sdk tools.
We don't bake tools from "canary" channel into images.

Also, I have checked and cmake 3.18 is installed without any problems in runtime:
```
steps:
      - run: echo "yes" | $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.18.1" --channel=3
```
See results in build: https://github.com/maxim-lobanov/test-repo/runs/1537169598?check_suite_focus=true

**Pull request closed without merging**
