### PR TITLE
Add brotli to linux images

### PR DESCRIPTION
**Pull request by vhiairrassary**
# Description
Add brotli to linux images
Approximate size: 730.0 kB (Installed size in Ubuntu 20.04: https://packages.ubuntu.com/focal/brotli)

Tests should already be included: https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/basic.sh#L94-L101

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by vhiairrassary** [comment]
Is there a way to get ubuntu checks run on that PR?

**Comment by vhiairrassary** [comment]
@maxim-lobanov It seems there was [an issue in the pipeline about geckodriver](https://github.visualstudio.com/virtual-environments/_build/results?buildId=77254&view=logs&j=f3215316-5135-57cb-291b-0903c8ad86f7&t=363259d8-0f0a-5fb4-2a1f-9a5fbec03447&l=46268). I rebased the commit. Is it possible to trigger the pipelines?

**Comment by maxim-lobanov** [comment]
Yep, it is known issue that was fixed recently by https://github.com/actions/virtual-environments/pull/1322
Could you please pull the latest master to your branch and I will restart builds? Sorry for inconvenience

**Comment by vhiairrassary** [comment]
No problem. I rebased the branch, you can restart them

**Pull request merged**
