### PR TITLE
Add zstd

### PR DESCRIPTION
**Pull request by imbsky**
This PR is part of #89.

### CODE REVIEW

**Comment by imbsky** [comment]
The installation code for macOS doesn't seem to be available from users at this time. Could you install zstd? You can install it via brew.

**Comment by al-cheb** [comment]
Hello, @imbsky 

Please do not forget to update packer templates:
[ubuntu1604.json ](https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1604.json) - ubuntu 16.04
[ubuntu1804.json](https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1804.json) - ubuntu 18.04
[Windows2016-Azure.json](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Azure.json) - windows server 2016
[Windows2019-Azure.json](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Azure.json) - windows server 2019

**Comment by imbsky** [comment]
Hi @al-cheb, I updated this PR according to your instructions!

**Comment by imbsky** [comment]
@al-cheb @sergey-akhalkov Thank you for your review 🙂

**Comment by imbsky** [comment]
@al-cheb @sergey-akhalkov @alepauly What is the status of this PR?

**Comment by alepauly** [comment]
> @al-cheb @sergey-akhalkov @alepauly What is the status of this PR?

sorry, it was just waiting for me. Approved, thanks for your contribution @imbsky !

**Comment by imbsky** [comment]
No, thank you, too!

**Comment by imbsky** [comment]
By the way, will you make changes for macOS installation?

**Comment by miketimofeev** [comment]
@imbsky let me take care of it. I will provide additional info inside the initial issue when it's ready.

**Comment by imbsky** [comment]
@miketimofeev Thank you!

**Pull request merged**
