### PR TITLE
[Ubuntu] docker: add debian bullseye images

### PR DESCRIPTION
**Pull request by EdJoPaTo**
# Description
With the release of Debian bullseye more and more containers are migrating from buster to bullseye.

I also included the latest release of alpine. The [Software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md) do not state how many versions should be kept for Docker images. Debian 9 is still within its LTS schedule. Alpine 3.11 is also still supported.

https://wiki.debian.org/LTS
https://www.alpinelinux.org/releases/

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by miketimofeev** [comment]
For reference:
Total reclaimed space is about 800 Mb.
@EdJoPaTo could you please remove the changes from the ubuntu-16 toolset as the version is being deprecated.

**Comment by miketimofeev** [comment]
> Debian 9 is still within its LTS schedule. Alpine 3.11 is also still supported.
The support for alpine 3.11 ends on 01 Nov 2021, for Debian 9 it's June 22

**Review by miketimofeev — APPROVED** [review]

**Review by al-cheb — APPROVED** [review]

**Review by MaksimZhukov — APPROVED** [review]

**Comment by miketimofeev** [comment]
@EdJoPaTo thanks for your contribution!

**Pull request merged**
