### PR TITLE
[Windows] Workaround for missing Edge webriver

### PR DESCRIPTION
**Pull request by miketimofeev**
# Description
Webdriver win64 for version 85.0.564.60 doesn't exist thus all windows builds are broken. Temporary hardcode 85.0.564.51 installation.

#### Related issue:
n\a

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by maxim-lobanov — APPROVED** [review]

**Review by AlenaSviridenko — APPROVED** [review]

**Comment by hutson** [comment]
Related: this is because the latest patch release of Release 85 for the Edge web driver does not have an x86 or x64 build - https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads

image

**Comment by maxim-lobanov** [comment]
> Related: this is because the latest patch release of Release 85 for the Edge web driver does not have an x86 or x64 build - https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads
> 
> image

We are working with Edge team to prevent such issues in future and provide better solution of getting latest available version for particular OS. For now, just push workaround

**Comment by hutson** [comment]
Local testing indicates this change works as expected. 👍 

Before change:

```bash
    ami: Downloading package from: https://msedgedriver.azureedge.net/85.0.564.60/edgedriver_win64.zip to path C:\Users\ADMINI~1\AppData\Local\Temp\edgedriver_win64.zip .
    ami: There is an error during package downloading:
```

After change:

```bash
    ami: Downloading package from: https://msedgedriver.azureedge.net/LATEST_RELEASE_85 to path C:\SeleniumWebDrivers\EdgeDriver\versioninfo.txt .
    ami: Download Microsoft Edge WebDriver...
    ami: Downloading package from: https://msedgedriver.azureedge.net/85.0.564.51/edgedriver_win64.zip to path C:\Users\ADMINI~1\AppData\Local\Temp\edgedriver_win64.zip .
    ami: Expand Microsoft Edge WebDriver archive...
```

> Note: I am building an AMI image using a slightly modified Azure config file.

**Pull request merged**
