### PR TITLE
Add support for Android build-tools-30.0.2 to Ubuntu images

### PR DESCRIPTION
**Pull request by moallemi**
# Description
This PR adds Android **build-tools-30.0.2** to linux images

## Check list
- [X] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [X] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by Darleev — APPROVED** [review]

**Review by AlenaSviridenko — APPROVED** [review]

**Comment by AlenaSviridenko** [comment]
Hi @moallemi, we have recently merged the PR with re-worked toolset structure https://github.com/actions/virtual-environments/pull/1420, could you please update your PR?

**Comment by moallemi** [comment]
Yes, sure

**Comment by moallemi** [comment]
@AlenaSviridenko Done

**Comment by Queenj30** [comment]
Duplicate of #517

**Pull request merged**
