### PR TITLE
Move gcloud to CLI tools section

### PR DESCRIPTION
**Pull request by mik-laj**
Hello,

CLI for other cloud providers is in "CLI tools" section, so I'm also moving gcloud to make it easier to find all of the cloud tools.

Best regards,
Kamil Breguła

# Description
New tool, Bug fixing, or Improvement?  
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.  
**For new tools, please provide total size and installation time.**

## Check list
- [x] Related issue / work item is attached
- [x] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [x] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by al-cheb** [comment]
Hello, @mik-laj 
Could you please remove your changes related to auto-generated documentation file and update the `https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1` script to include your changes with moving `Get-GoogleCloudSDKVersion` function?

**Comment by maxim-lobanov** [comment]
@mik-laj , any updates? Please update your PR accordingly to @al-cheb 's proposal. 
Or you can just log an issue in this repository and we will take care about this change

**Comment by mik-laj** [comment]
@maxim-lobanov @al-cheb Done

**Review by al-cheb — APPROVED** [review]

**Review by AlenaSviridenko — APPROVED** [review]

**Comment by maxim-lobanov** [comment]
Thank you for contribution! I will merge PR.

**Pull request merged**
