### PR TITLE
[Windows] add Android NDK 25

### PR DESCRIPTION
**Pull request by yujincheng08**
# Description
Update Android NDK to new LTS r25

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by ddobranic** [comment]
@yujincheng08 , hi! can you please pull the latest code? we removed default version. thank you!

**Comment by yujincheng08** [comment]
@ddobranic Done. Thanks for your reminder.

**Review by ddobranic — APPROVED** [review]

**Review by Thaddeus555555th — COMMENTED** [review]
yes

**Pull request merged**
