### PR TITLE
add buster layer to github runner's cache

### PR DESCRIPTION
**Pull request by arroyc**
This is to add buster image as part of the cache
#### Related issue:
#1358 
## Check list
- [X] Related issue / work item is attached

### CODE REVIEW

**Comment by maxim-lobanov** [comment]
Image size is 804 MB. Installation time is 12 seconds.

**Comment by maxim-lobanov** [comment]
@arroyc , could you please confirm that we need to add this image to all ubuntu (16.04, 18.04, 20.04)?

**Comment by kichalla** [comment]
Awesome!. Thanks @alepauly and @maxim-lobanov for the quick response on this. Are you also planning to update the following doc with the SHA digest just as you do for `stretch` image? (My team relies on this SHA digest)
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

**Comment by maxim-lobanov** [comment]
Yes, this documentation will be auto-updated on next image rollout (about 1 week)

**Comment by kichalla** [comment]
Great. Thanks @maxim-lobanov

**Comment by arroyc** [comment]
Thanks @maxim-lobanov  and @alepauly  .. for some reason I didn't get the notifications of this thread .. so sorry for delayed response ... all looks good so far ...

**Pull request merged**
