### PR TITLE
[Windows] Add sbt to Windows 2022 image

### PR DESCRIPTION
**Pull request by EwoutH**
# Description
Adds [sbt](https://github.com/sbt/sbt) to the Windows 2022 image. It's already installed for the Windows Server 2016 and 2019 images, and this PR adds it also to the 2022 image.

## Check list
- [ ] Related issue / work item is attached
- [x] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by miketimofeev** [comment]
Hi @EwoutH!
Have you tried using https://github.com/olafurpg/setup-scala action for your needs? Or do you need sbt for Azure DevOps builds?

**Comment by EwoutH** [comment]
Yes, I use that action frequently. The install time is somewhat longer if you're using the latest version and it isn't pre-installed on the image though. All other platforms provide a pre-installed sbt version, so it would be nice to make it consistent by also installing it on the Windows Server 2022 image.

**Comment by miketimofeev** [comment]
@EwoutH thanks, sounds reasonable as I thought the action takes only a few seconds to install sbt.
Could you also update the software generator?
https://github.com/actions/virtual-environments/blob/main/images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1#L79

**Comment by EwoutH** [comment]
Good catch, I update the software generator!

**Review by al-cheb — APPROVED** [review]

**Review by miketimofeev — APPROVED** [review]

**Review by MaksimZhukov — APPROVED** [review]

**Comment by miketimofeev** [comment]
@EwoutH thank you for the contribution! The changes will _probably_ be available later this week

**Pull request merged**
