### PR TITLE
Update clang on Ubuntu 20

### PR DESCRIPTION
**Pull request by AshUK**
# Description
Adds clang 11 to the clang installer and bumps the default version, tested on a private ubuntu server

#### Related issue:
#1882 

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by al-cheb** [comment]
Hello, @AshUK 
Could you please remove changes related to auto-generated documentation file Ubuntu2004-README.md ?

**Comment by miketimofeev** [comment]
@AshUK could you please pull the latest main? We've made some significant changes there so your branch is not working anymore.

**Comment by miketimofeev** [comment]
@AshUK looks like there is no clang-11 package for Ubuntu-20 yet
https://packages.ubuntu.com/search?keywords=clang-&searchon=names&suite=focal&section=all
Build failed with
```
==> azure-arm: E: Unable to locate package clang-11
==> azure-arm: E: Unable to locate package lldb-11
==> azure-arm: E: Unable to locate package lld-11
==> azure-arm: E: Unable to locate package clang-format-11
    azure-arm: Testing to make sure that script performed as expected, and basic scenarios work
    azure-arm: clang-11 was not installed

```

**Comment by AshUK** [comment]
@miketimofeev This looks to be true, the test server I have used seems to have had the llvm repository previously installed, I thought it was a clean server. I have updated the PR to use the external llvm installer when installing clang-11 on ubuntu 20.

What I am not unsure of is how install was successful on 16 and 18 as when searching the official ubuntu packages clang-11 is not available on these platform either.

@AlenaSviridenko can you please run all three pipelines again.

**Comment by miketimofeev** [comment]
@AshUK could you please pull the latest main to your branch? We've just fixed an issue, which breaks the builds https://github.com/actions/virtual-environments/pull/2184
I'll rerun the builds after that. Sorry for the inconvenience!

**Comment by miketimofeev** [comment]
@AshUK I'm afraid we forgot about the issue related to llvm https://github.com/actions/virtual-environments/issues/1536#issuecomment-698291544
Therefore it's better to wait until clang-11 is added to the official ubuntu to avoid the issue.

**Comment by maxim-lobanov** [comment]
I am closing this PR since as @miketimofeev mentioned we install clang only from default repo. Installing from llvm repo cause issues mentioned above. We will be able to accept this contribution when CLang is added to default repo.

**Pull request closed without merging**
