### PR TITLE
Update to Kind v0.8.1

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

# Description
New tool, Bug fixing, or Improvement?  Update version
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.  
Updated to latest kind. This supports Ipv6.

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by miketimofeev** [comment]
@tamalsaha could you please add functions to determine the latest kind version? In that case, we won't need to make a PR on every update.

**Comment by miketimofeev** [comment]
for windows it can be something like
```
function Get-LatestRelease {
    $latestRelease = Invoke-WebRequest https://api.github.com/repos/kubernetes-sigs/kind/releases/latest -UseBasicParsing
    $jsonContent = $latestRelease.Content | ConvertFrom-Json
    $versionPattern = '\d+(\.\d+){2,}'
    $tagName = $jsonContent.tag_name
    $latestVersion = [regex]::matches($tagName, $versionPattern).value
    return $latestVersion
}
```

**Comment by miketimofeev** [comment]
And this one for Linux
```
function GetLatestRelease () {
    curl --silent "https://api.github.com/repos/kubernetes-sigs/kind/releases/latest" |
    grep '"tag_name":' |
    sed -E 's/.*"([^"]+)".*/\1/' |
    sed 's/v//' # remove v prefix
}
```

**Comment by tamalsaha** [comment]
@miketimofeev , good idea. Mind opening a pr yourself? I don't know how things work in Windows.

**Comment by miketimofeev** [comment]
@tamalsaha can you create an issue with update kind request then?

**Comment by tamalsaha** [comment]
Done https://github.com/actions/virtual-environments/issues/952

**Pull request closed without merging**
