### PR TITLE
Add Xcode 12.1.1 RC  & Xcode 12.2 RC

### PR DESCRIPTION
**Pull request by AlenaSviridenko**
# Description
Adding Xcode 12.1.1 RC next to Xcode 12.1 since replacement didn't work well + adding just released Xcode 12.2 RC

## Check list
- [n\a] Related issue / work item is attached
- [n\a] Tests are written (if applicable)
- [n\a] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by maxim-lobanov — APPROVED** [review]

**Review by miketimofeev — APPROVED** [review]

**Comment by EwoutH** [comment]
@AlenaSviridenko Could you also please update the documentation when adding/updating images? ([macos-10.15-Readme.md](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) and [macos-11.0-Readme.md](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md) in this case)

**Comment by maxim-lobanov** [comment]
@EwoutH , Documentation is updated automatically when new image is deployed everywhere. New image with these changes will be deployed during next week

**Pull request merged**
