### PR TITLE
rust: Use rustup's minimal profile

### LINKED ISSUE #600: Use rustup's minimal profile and remove rust-docs component
**Tool information**
- Tool name: rustup
- Add or update? use `rustup set profile minimal` and remove `rust-docs` component
- Desired version: None
- Approximate size: None
- Rationale:
`rust-docs` component is rarely used on most Rust project CI, except some Rust linter 
or spelling checker.
Compare size with/without installing rust-docs:
```
400M    /home/lzutao/.rustup/toolchains/nightly-2020-03-19-x86_64-unknown-linux-gnu
733M    /home/lzutao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
```

Also, the Rust stable toolchain on Windows is not always up-to-date.
So many users may want to manually run `rustup update stable` on CI.
But `rust-docs` is large and contains of many files, which is slow for removing 
and reinstalling.
Travis uses minimal profile and doesn't install rust-docs component with no problem.

**Area for Triage**: Rust

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

If I could figure out how to do that.

### PR DESCRIPTION
**Pull request by lzutao**
Close Linux and Windows part of #600.

### CODE REVIEW

**Comment by lzutao** [comment]
The windows2019 build looks spurious. But I'm not sure about that.

**Comment by lzutao** [comment]
windows2019 build failed with virus update errors:
```
==> vhd: Provisioning with powershell script: C:\agent\_work\7\s\images\win/scripts/Installers/Windows2019/Run-Antivirus.ps1
    vhd: Make sure windefend is going to start
    vhd: Waiting for windefend to report as running
    vhd: Run antivirus
    vhd: Scan starting...
    vhd: CmdTool: Failed with hr = 0x800106BA. Check C:\Users\packer\AppData\Local\Temp\MpCmdRun.log for more information
    vhd: Set antivirus parmeters
==> vhd: Update-MpSignature : Virus and spyware definitions update was completed with errors.
==> vhd: At C:\Windows\Temp\script-5e786450-eb9a-2382-6cfc-61d52d0b7303.ps1:24 char:1
==> vhd: + Update-MpSignature
==> vhd: + ~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : NotSpecified: (MSFT_MpSignature:ROOT\Microsoft\...SFT_MpSignature) [Update-MpSignature],
==> vhd:     CimException
==> vhd:     + FullyQualifiedErrorId : HRESULT 0x800106b5,Update-MpSignature
```

**Comment by maxim-lobanov** [comment]
@lzutao , Could you please pull the latest master to your branch? Windows builds failed due to known issue with Antivirus and it should be fixed in master. Sorry for inconvinience.
Changes look good, just want to get green checks.

**Comment by lzutao** [comment]
Done. Thanks for taking a look.

**Comment by lzutao** [comment]
The windows2019 build failed. I don't understand what it is:
```
2020-03-24T06:42:32.8128374Z ==> vhd: Provisioning with Powershell...
2020-03-24T06:42:32.8143593Z ==> vhd: Provisioning with powershell script: C:\agent\_work\7\s\images\win/scripts/Installers/Update-DotnetTLS.ps1
2020-03-24T06:42:34.9771882Z ==> vhd: Restarting Machine
2020-03-24T06:42:35.1129318Z ==> vhd: Waiting for machine to restart...
2020-03-24T06:42:35.2420932Z ==> vhd: A system shutdown is in progress.(1115)
2020-03-24T06:43:16.1877403Z     vhd: pkrvm6x3moo0sp4 restarted.
2020-03-24T06:43:16.1892442Z ==> vhd: #< CLIXML
2020-03-24T06:43:16.1908932Z ==> vhd: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
2020-03-24T06:43:16.1922225Z ==> vhd: Machine successfully restarted, moving on
2020-03-24T06:43:16.1940570Z ==> vhd: Provisioning with Powershell...
2020-03-24T06:43:16.1953685Z ==> vhd: Provisioning with powershell script: C:\agent\_work\7\s\images\win/scripts/Installers/Install-ContainersFeature.ps1
2020-03-24T06:43:19.0389352Z     vhd: Install Containers feature
2020-03-24T06:44:08.1484462Z     vhd:
2020-03-24T06:44:08.1499730Z     vhd: Success Restart Needed Exit Code      Feature Result
2020-03-24T06:44:08.1532260Z     vhd: ------- -------------- ---------      --------------
2020-03-24T06:44:08.1558413Z     vhd: True    Yes            SuccessRest... {Containers}
2020-03-24T06:44:08.1559426Z     vhd: WARNING: You must restart this server to finish the installation process.
2020-03-24T06:44:08.7158409Z     vhd: Skipping installation of Hyper-V feature
2020-03-24T06:44:08.7190427Z ==> vhd: Restarting Machine
2020-03-24T06:44:08.9576932Z ==> vhd: Waiting for machine to restart...
2020-03-24T06:44:09.0828798Z ==> vhd: A system shutdown is in progress.(1115)
2020-03-24T06:45:18.4913177Z     vhd: pkrvm6x3moo0sp4 restarted.
2020-03-24T06:45:18.4928728Z ==> vhd: #< CLIXML
2020-03-24T06:45:18.4947950Z ==> vhd: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
2020-03-24T06:45:18.4963976Z ==> vhd: Machine successfully restarted, moving on
2020-03-24T06:45:18.4984374Z ==> vhd: Provisioning with Powershell...
2020-03-24T06:45:18.5055386Z ==> vhd: Provisioning with powershell script: C:\windows\ServiceProfiles\NetworkService\AppData\Local\Temp\powershell-provisioner024665367
2020-03-24T06:50:48.6785342Z ==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...
2020-03-24T06:50:48.6806167Z ==> vhd: Removing the created Deployment object: 'pkrdp6x3moo0sp4'
2020-03-24T06:51:33.8622403Z ==> vhd: Removing the created Deployment object: 'kvpkrdp6x3moo0sp4'
2020-03-24T06:52:19.0131126Z ==> vhd: 
2020-03-24T06:52:19.0146534Z ==> vhd: Cleanup requested, deleting resource group ...
2020-03-24T07:01:49.7187292Z ==> vhd: Resource group has been deleted.
2020-03-24T07:01:49.7237968Z Build 'vhd' errored: Error processing command: Error uploading ps script containing env vars: Error uploading file to $env:TEMP\winrmcp-0b21405a-c548-4cd1-5d9b-10dd9062bc44.tmp: Couldn't create shell: unknown error Post https://10.1.3.53:5986/wsman: read tcp 10.1.3.11:59293->10.1.3.53:5986: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2020-03-24T07:01:49.7240283Z 
2020-03-24T07:01:49.7241104Z ==> Some builds didn't complete successfully and had errors:
2020-03-24T07:01:49.7242620Z --> vhd: Error processing command: Error uploading ps script containing env vars: Error uploading file to $env:TEMP\winrmcp-0b21405a-c548-4cd1-5d9b-10dd9062bc44.tmp: Couldn't create shell: unknown error Post https://10.1.3.53:5986/wsman: read tcp 10.1.3.11:59293->10.1.3.53:5986: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2020-03-24T07:01:49.7244361Z 
```

**Pull request merged**
