### PR TITLE
Adds .NET 6 

### PR DESCRIPTION
**Pull request by nshenoy**
# Description
Adds .NET 6.0 to toolsets for Linux and Windows. The changes to macos were omitted per the [contributions guidelines](https://github.com/actions/virtual-environments/blob/main/CONTRIBUTING.md#macos).

## Check list
- [x] Related issue / work item is attached
- [x] Tests are written (already covered by existing DotnetSDK.Tests.ps1)
- [] Documentation is updated (if applicable)
- [x] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by tabman83 — APPROVED** [review]

**Review by diogonborges — APPROVED** [review]
LGTM

**Comment by YvesCandel** [comment]
When is this to be merged?

**Review by vai — APPROVED** [review]
Yes please

**Review by davidandradeduarte — APPROVED** [review]
👍

**Comment by carlreid** [comment]
I _think_ it was decided that future .NET versions won't get installed by default anymore ([read here](https://github.com/actions/virtual-environments/issues/4424#issuecomment-967012616)).  
  
If anyone is blocked by this or while we wait, you can still do a step such as:
```yaml
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
```

**Pull request closed without merging**
