### PR TITLE
Update SSDT to 15.9.3

### PR DESCRIPTION
**Pull request by m-minasyan**
This PR related to the issue #484. It update SSDT version for VS 2017 to the latest version (15.9.3).

### CODE REVIEW

**Comment by miketimofeev** [comment]
Do we install `SQL Server Integration Services` that mentioned in https://github.com/actions/virtual-environments/issues/484?

**Comment by m-minasyan** [comment]
> Do we install `SQL Server Integration Services` that mentioned in #484?

I think yes, because we have `SQL Server Integration Services Designer` line in `Validate-SSDT.ps1`

**Comment by vmapetr** [comment]
> /azp run windows2016, windows2019

I'm not sure if validation image on win 2019 is required here.

**Comment by m-minasyan** [comment]
> BTW, As I can see, SSDT is absent on Win 2019 image, shouldn't it be added as well?
SSDT for Visual Studio 2019 is included in it. There's no SSDT standalone installer for Visual Studio 2019.

**Pull request merged**
