### PR TITLE
Update CMake on Linux

### PR DESCRIPTION
**Pull request by al-cheb**
Issue:
https://github.com/actions/virtual-environments/issues/56

Fix:
Update Cmake version to  Cmake 3.15.4

### CODE REVIEW

**Comment by alepauly** [comment]
@al-cheb #141 attempts to update to 3.15.5, any reason we can't do that here? (that other one is blocked on conflicts right now)

**Comment by al-cheb** [comment]
@alepauly I have checked installed CMake version on MacOS, Windows hosted agents. These images contain CMake 3.16.2. Would it make sense to update Cmake version to 3.16.2 or 3.15.6 on Ubuntu images?

**Comment by alepauly** [comment]
> 
> 
> @alepauly I have checked installed CMake version on MacOS, Windows hosted agents. These images contain CMake 3.16.2. Would it make sense to update Cmake version to 3.16.2 or 3.15.6 on Ubuntu images? The second choice we can rework script to install Cmake using apt tool - https://apt.kitware.com/ .

If it's easy to install 3.16.2 for consistency I think it makes sense. We can defer changing install mechanism for later as needed. I dont think we need to do it/risk it now.

**Comment by zbeekman** [comment]
FWIW adding the Kitware APT repo, say to [`repos.sh`](https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/base/repos.sh) will make upgrading and pinning CMake a little easier. I'm happy to submit a PR if you like.

**Pull request merged**
