### PR TITLE
Add additional agent info

### PR DESCRIPTION
**Pull request by al-cheb**
Request info: https://github.com/actions/virtual-environments-internal/issues/208

Provide more virtual environment details in the runner. 

- The OS version
- The image version
- A link to the markdown file with image details

Default file path for imagedata.json:
| Name | Path| Packer Variable | Packer script |
|--------|------|------------------|---------------|
| Ubuntu 16.04 | /imagegeneration/imagedata.json | imagedata_file | installers/preimagedata.sh |
| Ubuntu 18.04 | /imagegeneration/imagedata.json | imagedata_file | installers/preimagedata.sh |
| Windows Server 2016 | C:\imagedata.json | imagedata_file | Installers/Update-ImageData.ps1 |
| Windows Server 2019 | C:\imagedata.json | imagedata_file | Installers/Update-ImageData.ps1 |
| macOS 10.15 | /Users/runner/imagedata.json | - | preimagedata.sh |

Example imagedata.json output:

Ubuntu 16.04

```
[
  {
    "group": "Operating System",
    "detail": "Ubuntu\n16.04.6\nLTS"
  },
  {
    "group": "Virtual Environment",
    "detail": "Environment: ubuntu-16.04\nVersion: 20200301.1\nIncluded Software: https://github.com/actions/virtual-environments/blob/ubuntu16/20200301.1/images/linux/Ubuntu1604-README.md"
  }
]
```

Ubuntu 18.04

```
[
  {
    "group": "Operating System",
    "detail": "Ubuntu\n18.04.4\nLTS"
  },
  {
    "group": "Virtual Environment",
    "detail": "Environment: ubuntu-18.04\nVersion: 20200301.1\nIncluded Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200301.1/images/linux/Ubuntu1804-README.md"
  }
]
```

Windows 2016

```
[
  {
    "group": "Operating System",
    "detail": "Microsoft Windows Server 2016\n10.0.14393\nDatacenter"
  },
  {
    "group": "Virtual Environment",
    "detail": "Environment: windows-2016\nVersion: 20200301.1\nIncluded Software: https://github.com/actions/virtual-environments/blob/win16/20200301.1/images/win/Windows2019-Readme.md"
  }
]

```
Windows 2019

```
[
  {
    "group": "Operating System",
    "detail": "Microsoft Windows Server 2019\n10.0.17763\nDatacenter"
  },
  {
    "group": "Virtual Environment",
    "detail": "Environment: windows-2019\nVersion: 20200301.1\nIncluded Software: https://github.com/actions/virtual-environments/blob/win19/20200301.1/images/win/Windows2019-Readme.md"
  }
]
```

macOS 10.15

```
[
  {
    "group": "Operating System",
    "detail": "macOS\n10.15.3\n19D76"
  },
  {
    "group": "Virtual Environment",
    "detail": "Environment: macos-10.15\nVersion: 20200301.1\nIncluded Software: https://github.com/actions/virtual-environments/tree/master/images/macos"
  }
]
```

### CODE REVIEW

**Comment by maxim-lobanov** [comment]
May be, we should use $HOME folder everywhere for consistency,
- `/Users/runner/` on macOS
- `/home/runner` on Ubuntu
- `C:\` on Windows

**Comment by frankzo** [comment]
@al-cheb I use this to apply some extra info to our own agents, but that info is not displayed in Azure DevOps. (groups missing in "initializing job") , I however do see this info displayed when choosing the MS hosts. Missing something?

**Comment by miketimofeev** [comment]
@frankzo As far as I know there is an additional logic on the hosted-agents side to display this data. That explains why it's not shown using self-hosted ones.

**Comment by frankzo** [comment]
@miketimofeev Thanks. I was able to set the image version with the setx from initialize-vm.ps1 so was hoping this would work too.

**Comment by maxim-lobanov** [comment]
@frankzo , yep. As Mikhail mentioned, currently, it works only for Hosted agents.

Additional context:
We have an additional logic that copies this `imagedata.json` file to the agent folder: 
```
Copy /imagegeneration/imagedata.json file to the /home/vsts/agents/2.182.1/.setup_info target
```
(Example for Ubuntu but general logic should be pretty clear - copy file to the root of agent folder)

On Hosted machines, we have to do it after azure-pipelines-agent installation since agent installation is not covered by image-generation.
On Self-Hosted machine, I guess you can just copy this file once after agent installation and it should work.

**Comment by frankzo** [comment]
That worked like a charm.  I use scale sets agents in Azure DevOps which are installed by an extension that set the agent directory (Windows) to c:\agent by default. 

I added this section to my Packer json just before sysprep:

`        {
                "type": "file",
                "source": "C:\\imagedata.json",
                "destination": "C:\\Agent/.setup_info"
        }`

**Pull request merged**
