### PR TITLE
PostgreSQL not Postgre SQL

### PR DESCRIPTION
**Pull request by pashagolub**
https://wiki.postgresql.org/wiki/Postgres

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by maxim-lobanov — APPROVED** [review]

**Comment by heroku-miraheze** [comment]
Failed, and is the same.

**Comment by heroku-miraheze** [comment]
Please, close it immediately.

**Comment by pashagolub** [comment]
> 
> 
> Please, close it immediately.

Why that?

**Pull request merged**
