### PR TITLE
Remove unnecessary Node.js related dependencies

### LINKED ISSUE #427: Cache is large on macos-latest
👋 When setting up caching via `actions/cache`, it's common and recommended to cache `~/.npm` after running npm install/ci.

On macOS, this directory is pre-populated with npm packages that are potentially not related to the user's build and is over 1 GB in size. This limits the ability to cache build dependencies due to size constraints and slows down caching due to the larger cache size.

See https://github.com/actions/cache/issues/187

This applies to other ecosystems like Gradle as well

### PR DESCRIPTION
**Pull request by imbsky**
Closes #427

### CODE REVIEW

**Comment by imbsky** [comment]
CC: @maxim-lobanov @joshmgross

**Comment by maxim-lobanov** [comment]
@imbsky , I think the initial issue was about macOS (I have put some info there).
As for Linux / Windows, yep, probably some preinstalled packages are unnecessary but, unfortunately, we can't predict if it breaks someone.
Is it real issue on Windows / Linux?

**Comment by imbsky** [comment]
No, this should happen on all operating systems. (Because you used npm to install some packages. and this is why I didn't install yarn using npm in this PR.) Also, for general use, a global installation of these tools is more likely to destroy the user's environment.

**Comment by imbsky** [comment]
By the way, I can't update macOS code because it's not open source, so could you do that? Note that you need to install yarn via brew. (It should not be installed via npm for the above reasons.)

**Comment by imbsky** [comment]
As a less clean fix, removing the contents of the npm cache directory after a global install is not a bad option. But, it's better to remove the unnecessary tools from code and install yarn via brew.

**Comment by imbsky** [comment]
This should not happen if you are using yarn. At least in my environment. So I strongly suspect that the problem is caused by the installation of unnecessary tools via npm.

**Comment by imbsky** [comment]
I just resolved the conflict. Please let me know if you have any additional questions or concerns.

**Comment by maxim-lobanov** [comment]
I am still concerned about removing those packages because customers' pipelines can depend on them and will start fail after these changes.
For example, Lerna. It was added recently, in scope of this issue #286 so your changes remove this package and will cause regression.
The same for other packages, they were added by customers' requests

**Comment by imbsky** [comment]
Well, I don't think it will take that long to install lerna. Also, installing the npm libraries globally is disruptive and shouldn't have been done casually in CI's VM image in the first place. 99% of people install dependencies from a package.json. The problems that this causes are primarily due to actions that deviate from the recommended workflow.

**Comment by alepauly** [comment]
Thanks for the PR @imbsky but we can't stop installing those packages without some preparation. Your comments are definitely heard and we can continue to discuss the approach of [not] installing packages by default but I'll close this PR since this would definitely break existing users.

**Comment by imbsky** [comment]
I see. For example, what about running the cache clean command after installation? If you okay with that, I will open a PR to do it.

**Comment by imbsky** [comment]
I think this is the simplest solution that doesn't break the existing environment.

**Comment by maxim-lobanov** [comment]
@imbsky , 
I think `running the cache clean command after installation` should work for us.

**Comment by imbsky** [comment]
Okay

**Comment by imbsky** [comment]
There is a lot of code to install npm packages, so I think it's inefficient to purge cache everywhere every time. I would like to run it once when the entire installation process is complete. Is there a way to do that?

**Comment by maxim-lobanov** [comment]
@imbsky , We can add separate script and put it to the packer template as a last step

**Comment by imbsky** [comment]
Oh, I see.

**Pull request closed without merging**
