### PR TITLE
openssl.sh: follow better Homebrew norms.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Tweak the logic here to avoid messing with the typical Homebrew installation while still providing the necessary files outside of Homebrew that are needed.

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by miketimofeev — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
@maxim-lobanov Updated based on https://github.com/actions/virtual-environments/pull/1889. Please rereview, thanks!

**Comment by maxim-lobanov** [comment]
@MikeMcQuaid , we need to postpone merging this PR a bit.
Currently, Python is looking at `/usr/local/opt/openssl` and it is broken after these changes. We are working to rebuild it

**Comment by MikeMcQuaid** [comment]
> Currently, Python is looking at `/usr/local/opt/openssl` and it is broken after these changes. We are working to rebuild it

@maxim-lobanov How is Python being installed? Is this the one from `python.sh`? If so, is that script run before or after the `openssl.sh` one?

**Comment by maxim-lobanov** [comment]
> > Currently, Python is looking at `/usr/local/opt/openssl` and it is broken after these changes. We are working to rebuild it
> 
> @maxim-lobanov How is Python being installed? Is this the one from `python.sh`? If so, is that script run before or after the `openssl.sh` one?

No, on images we support a bunch of different Python (3.5, 3.6, 3.7, 3.8, 3.9) versions and we build them from source code.
Currently, it contains some hardcoded paths to point to openssl 1.0.2: https://github.com/actions/python-versions/blob/main/builders/macos-python-builder.psm1#L42

**Comment by MikeMcQuaid** [comment]
> No, on images we support a bunch of different Python (3.5, 3.6, 3.7, 3.8, 3.9) versions and we build them from source code.
> Currently, it contains some hardcoded paths to point to openssl 1.0.2: https://github.com/actions/python-versions/blob/main/builders/macos-python-builder.psm1#L42

Which of those versions fail to build without OpenSSL 1.0.x installed (i.e. fail with OpenSSL 1.1.x)? Are there logs I can look at anywhere?

**Comment by maxim-lobanov** [comment]
> > No, on images we support a bunch of different Python (3.5, 3.6, 3.7, 3.8, 3.9) versions and we build them from source code.
> > Currently, it contains some hardcoded paths to point to openssl 1.0.2: https://github.com/actions/python-versions/blob/main/builders/macos-python-builder.psm1#L42
> 
> Which of those versions fail to build without OpenSSL 1.0.x installed (i.e. fail with OpenSSL 1.1.x)? Are there logs I can look at anywhere?

After removing symlink `/usr/local/opt/openssl`, Python 3.7.0+ fails on commands:
```
./python -m ensurepip
./python -m pip install --ignore-installed pip
```
with errors like 
```
vsphere-clone: Requirement already satisfied: setuptools in /Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (47.1.0)
    vsphere-clone: Requirement already satisfied: pip in /Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (20.1.1)
==> vsphere-clone: WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
==> vsphere-clone: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
==> vsphere-clone: WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
==> vsphere-clone: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
==> vsphere-clone: WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
==> vsphere-clone: WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
    vsphere-clone: Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
==> vsphere-clone: ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
==> vsphere-clone: ERROR: No matching distribution found for pip
```

It is from your build: https://github.visualstudio.com/virtual-environments/_build/results?buildId=86347&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=7f6ff0d4-adc5-5557-eba3-0604338bbbf7
Try to search `toolset.ps1` installation step.

**Comment by MikeMcQuaid** [comment]
@maxim-lobanov Could you rerun the build? I was on vacation and want to take another look now but the logs are gone 😭. Thanks!

**Comment by maxim-lobanov** [comment]
@MikeMcQuaid , we are going to deprecate openssl 1.0.2 fully and set 1.1 as default in 3 weeks. See details in https://github.com/actions/virtual-environments/issues/2089
May be we can wait for deprecation date and this code will be removed fully. Does it work for you?

**Comment by MikeMcQuaid** [comment]
@maxim-lobanov Yup, that works much better for me. Closing this in favour of that, thanks again!

**Pull request closed without merging**
