### PR TITLE
Add Office/SharePoint development

### PR DESCRIPTION
**Pull request by dsame**
Add  VS2017 Workload with ID=Microsoft.VisualStudio.Workload.Office

according to https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019#officesharepoint-development

### CODE REVIEW

**Comment by miketimofeev** [comment]
@dsame @maxim-lobanov let's add it to Win19 image as well for consistency

**Comment by miketimofeev** [comment]
Noticed that Win19 already has this component

**Comment by alepauly** [comment]
Closing since this will require server deployment, won't implement.

**Comment by VerdonTrigance** [comment]
@alepauly Guys you can't just shovel this problem to the back burner. We will not be able to build SharePoint 2013 solutions any more. You know that?

**Comment by vijayma** [comment]
@VerdonTrigance We will install the office components on VS 2017/2019 images. We think this will be sufficient to meet your needs. But, can you share a simple project that we can validate with?

**Comment by VerdonTrigance** [comment]
> @VerdonTrigance We will install the office components on VS 2017/2019 images. We think this will be sufficient to meet your needs. But, can you share a simple project that we can validate with?

I don't have any public projects yet.

**Comment by VerdonTrigance** [comment]
> @VerdonTrigance We will install the office components on VS 2017/2019 images. We think this will be sufficient to meet your needs. But, can you share a simple project that we can validate with?

Hey, what is going on?

```
##[error]This job was blocked because it uses the hosted agent vs2015-win2012r2 which was permanently removed on April 2nd, 2020.  See https://aka.ms/blocked-hosted-agent for more information.
,##[error]The remote provider was unable to process the request.
```

Why it has been deleted without providing Sharepoint SDK on a new images?

`##[error]MVideo.Acquiring.SpDAL\Models\SpListItemClaim.cs(1,17): Error CS0234: The type or namespace name 'SharePoint' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)`

**Pull request closed without merging**
