### PR TITLE
[Ubuntu] Revert $BASH_ENV variable

### PR DESCRIPTION
**Pull request by miketimofeev**
# Description
It turned out that $BASH_ENV causes some issues since updated PATH is not propagated to other shells like pwsh.
Reverts https://github.com/actions/virtual-environments/pull/2826

#### Related issue:
https://github.com/actions/virtual-environments/issues/2978

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by maxim-lobanov — APPROVED** [review]

**Comment by catthehacker** [comment]
@miketimofeev
*I've rambled a bit about `/etc/environment` && `/etc/profile` && shells here: https://github.com/nektos/act/pull/570#issuecomment-801560100*

For `pwsh` that is invoked without `-l`/`-login`, equivalent would be to create `$profile.AllUsersCurrentHost` or `$profile.AllUsersAllHosts` and add those variables in that file.
```powershell
$profile | gm -MemberType NoteProperty | % { return [pscustomobject]@{ Type = $_.Name ; Location = $profile."$($_.Name)" }}
```

image

e.g.:
```powershell
$env:XDG_CONFIG_HOME = "${env:HOME}/.config"
# or
$env:PATH = "$($env:PATH)$([IO.Path]::PathSeparator)$($env:HOME)/.dotnet/tools"
# or
$env:PATH = ('{0}{1}{2}/.dotnet/tools' -f $env:PATH, [IO.Path]::PathSeparator, $env:HOME)
```

Unfortunately I do not know how `zsh` will behave and how to fix it since I don't use it but from http://zsh.sourceforge.net/Intro/intro_3.html it appears that `.zshenv` could be used if it was put in `/etc/skel`.

**Comment by cognifloyd** [comment]
Aargh. This just broke things for me because now ~/.local/bin isn't on the PATH anymore.

**Comment by cognifloyd** [comment]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun
> Commands run using non-login shells by default

And on my ubuntu jobs, it is running this shell: `bash --noprofile --norc -eo pipefail {0}`

So, .bashrc doesn't get loaded now (`--norc`) whereas the profile.d entries WERE getting loaded by default.

**Comment by miketimofeev** [comment]
@cognifloyd we're going to get it back soon, but using another approach. Sorry for the inconvenience

**Review by phuchau1989 — APPROVED** [review]

**Pull request merged**
