### PR TITLE
[Windows] Set PHP-7.4 as default

### PR DESCRIPTION
**Pull request by al-cheb**
# Description
Currently, during image generation process we install the latest version of PHP. At time of writing the current version of PHP is 8.0. One of the dependencies of PHP 8.0 is the `visualstudio2019buildtools` package which causes another issue  https://github.com/actions/virtual-environments/issues/1470.
```
2020-11-30T14:08:31.7820834Z     vhd: By installing you accept licenses for the packages.
2020-11-30T14:08:33.2822538Z     vhd: Progress: Downloading visualstudio2019buildtools 16.8.2.0... 100%
2020-11-30T14:08:34.1117278Z     vhd: Progress: Downloading chocolatey-visualstudio.extension 1.8.1... 100%
2020-11-30T14:08:35.4864619Z     vhd: Progress: Downloading dotnetfx 4.8.0.20190930... 100%
2020-11-30T14:08:37.0665171Z     vhd: Progress: Downloading chocolatey-dotnetfx.extension 1.0.1... 100%
2020-11-30T14:08:37.0669457Z     vhd: Progress: Downloading visualstudio-installer 2.0.1... 100%
2020-11-30T14:08:41.3145424Z     vhd: Progress: Downloading php 8.0.0... 100%
```

PS: choco list with the flag returns only the latest version of a package:
```
-a, --all, --allversions, --all-versions
     AllVersions - include results from all versions
```
Example:
```
PS > choco list -e php -a -r
php|8.0.0
```

#### Related issue:
https://github.com/actions/virtual-environments-internal/issues/1534
## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by AlenaSviridenko — APPROVED** [review]

**Comment by al-cheb** [comment]
@gep13, Hi,
Do you have any idea how to parse all versions from `https://chocolatey.org/packages/php#versionhistory` list for PHP-7.4?

```
PS > choco list -e php -a -r
php|8.0.0
```

**Comment by gep13** [comment]
@al-cheb are you saying that this command:

```
choco list -e php -a -r
```

Isn't giving you a list of all versions?  I have just run it on my machine, and I get lots of versions returned:

image

**Comment by gep13** [comment]
@al-cheb actually... hold on a second...

The above screenshot was from the latest beta release of Chocolatey.  I can confirm that with 0.10.15 version of Chocolatey installed, I can replicate the issue that you are seeing.

If possible, can you upgrade to the latest pre-release of Chocolatey, i.e.

```
choco upgrade chocolatey --pre
```

And you will get all versions returned.

**Comment by al-cheb** [comment]
@gep13, Thank you. I will try to upgrade to the latest pre-version.

**Comment by shivammathur** [comment]
@al-cheb This should be fixed in chocolatey as [`vcredist140`](https://chocolatey.org/packages/vcredist140) should be enough to install `PHP 8.0.0`. It does not require `visualstudio2019buildtools`. I have created an issue there chocolatey-community/chocolatey-coreteampackages#1587

**Review by maxim-lobanov — APPROVED** [review]

**Comment by maxim-lobanov** [comment]
@shivammathur , thank you for logging an issue for choco package!
Yes, as Alex mentioned, installation of `visualstudio2019buildtools` on CI machines bring a lot of pain and break Visual Studio behavior.
On local box, you just have two separate command line tools for Visual Studio and Visual Studio Build Tools.
On CI machines, you can't select them this way and installation of Visual Studio Build Tools breaks some use-cases (override Visual Studio behavior).

**Pull request merged**
