### PR TITLE
Fix Vcpkg output

### PR DESCRIPTION
**Pull request by dibir-magomedsaygitov**
# Description
In scope of this PR we are fixing Vcpkg version output on all images

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by miketimofeev — APPROVED** [review]

**Review by AlenaSviridenko — APPROVED** [review]

**Review by dmitry-shibanov — APPROVED** [review]

**Review by maxim-lobanov — APPROVED** [review]

**Comment by Andrewjlucas1** [comment]
#2349

**Comment by Andrewjlucas1** [comment]
#
[output.pdf](https://github.com/actions/virtual-environments/files/5741053/output.pdf)

**Comment by Andrewjlucas1** [comment]
#

- [ ] 

-

**Pull request merged**
