### PR TITLE
Add WiX v3 to Windows 2022.

### PR DESCRIPTION
**Pull request by barnson**
Move WiX to tools and stop installing WiX Votive VSIX, which isn't
needed for build.

# Description
New tool, Bug fixing, or Improvement?
_Improvement: Bringing WiX v3 to Windows2022 (as in Windows2019 and Windows2016)_

Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.
_The WiX Votive VSIX isn't needed for build (it's IDE project system only), so this change moves WiX out of the VS realm into tools._

#### Related issue:
https://github.com/actions/virtual-environments/issues/4419

## Check list
- [x] Related issue / work item is attached
- [x] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [x] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by barnson** [comment]
@al-cheb : https://github.com/actions/virtual-environments/pull/4449

**Comment by al-cheb** [comment]
@barnson , Thank you. The pr has been merged. You can merge the main branch.

**Comment by barnson** [comment]
@al-cheb, rebased so I'm up to date for the moment. :)

**Review by miketimofeev — APPROVED** [review]

**Review by al-cheb — APPROVED** [review]

**Comment by miketimofeev** [comment]
@barnson thank you for your contribution!

**Pull request merged**
