### PR TITLE
Update to Kind v0.7.0

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by kaylangan** [comment]
Dupe of #158

**Comment by tamalsaha** [comment]
@kaylangan, #158 does not update the windows version, FYI

**Comment by kaylangan** [comment]
Can you update this to just update the non-README files? We update those once the change has been deployed.

**Comment by tamalsaha** [comment]
Done!

**Comment by kaylangan** [comment]
@prativen @shashankbarsin @azooinmyluggage, can you take a look?

**Comment by miketimofeev** [comment]
@alepauly I've generated images with kind 0.7.0 and everything looks good at first glance

**Comment by alepauly** [comment]
thanks @tamalsaha and @miketimofeev!

**Review by Thhj9 — APPROVED** [review]

**Review by Thhj9 — APPROVED** [review]

**Pull request merged**
