### PR TITLE
Update readmes

### PR DESCRIPTION
**Pull request by jsoref**
# Description
New tool, Bug fixing, or Improvement?  
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.  
**For new tools, please provide total size and installation time.**

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by maxim-lobanov** [comment]
We shouldn't modify documentation manually. It is auto-generated.

**Comment by jsoref** [comment]
Can you kick it to have current accurate information?

**Comment by maxim-lobanov** [comment]
We are updating documentation when deployment is finished. Usually, it takes 3-4 days. Currently, it is in progress so docs are not updated yet.

If you would like to get actual documentation for image that are currently used in your build, you can find it in `Set up Job` step: 
image

**Comment by jsoref** [comment]
From what date? Some of the items listed here were dated the 8th, today's the 18th.

Also, what would it take to get you to spell `Windows` with a capital `W` for the Features line?

I get that GitHub wants to act independently of Microsoft, but even so, Windows is a major brand...

**Pull request closed without merging**
