### PR TITLE
Remove Ubuntu20 mysql workaround

### PR DESCRIPTION
**Pull request by ddobranic**
# Description
Bug fix for #4799 - [Ubuntu] Issue with libstdc++ cannot allocate memory in static TLS block. Remove old workaround since it is not needed as new versions of MySQL are available

#### Related issue:
#4799
## Check list
- [x] Related issue / work item is attached
- [x] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by mikhailkoliada — CHANGES_REQUESTED** [review]
Remove the init.d script too, as the deb distribution was incomplete and we had to port it manually from ubuntu.

**Comment by miketimofeev** [comment]
> Remove the init.d script too, as the deb distribution was incomplete and we had to port it manually from ubuntu.

@ddobranic this one https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/helpers/mysql-service-helper.sh

**Review by miketimofeev — APPROVED** [review]

**Review by ball144love — APPROVED** [review]

**Pull request merged**
