### PR TITLE
Ubuntu Bionic/Focal: Add GCC 11

### LINKED ISSUE #3280: Add GCC 11
Today GCC 11.1 [was released](https://gcc.gnu.org/pipermail/gcc/2021-April/235922.html), the first stable release of GCC 11. 

Currently GCC gets installed using the [gcc.sh](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/gcc.sh) installer script, using the versions in the [toolset-2004.json](https://github.com/actions/virtual-environments/blob/main/images/linux/toolsets/toolset-2004.json#L253) and [toolset-1804.json](https://github.com/actions/virtual-environments/blob/main/images/linux/toolsets/toolset-1804.json#L251) files. It uses the [ubuntu-toolchain-r/test](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test) repository, which doesn't have gcc-11 available.

At this moment, a stable GCC 11 version is not yet available on either [Ubuntu packages](https://packages.ubuntu.com/search?keywords=gcc-11&searchon=names&suite=all&section=all) (so not for focal-updates) or [Debian packages](https://packages.debian.org/search?keywords=gcc-11&searchon=names&suite=all&section=all) (only on experimental), which is where the complication starts.

Options to install GCC-11:
 - Building from source
 - Building once and caching/hosting somewhere
 - Using experimental toolchain
 - Waiting for package managers to update
 - More?

Lets use this issue to discuss how GCC 11 can be installed best on the Ubuntu images.

> **Tool information**
> - Tool name: GCC (GNU Compiler Collection)
> - Tool license: [Modified GNU General Public License version 3](https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html)
> - Add or update? Update
> - Desired version: [11](https://gcc.gnu.org/gcc-11/)
> - Approximate size: 199 MB installed
> 
> **Area for Triage**: C/C++
> 
> **Question, Bug, or Feature?**: Feature
> 
> **Virtual environments affected**
> - [x] Ubuntu 18.04
> - [x] Ubuntu 20.04
> 
> **Can this tool be installed during the build?**
> Yes
> 
> **Tool installation time in runtime**
> Probably about the same other GCC versions
> 
> **Are you willing to submit a PR?**
> Depends

### PR DESCRIPTION
**Pull request by EwoutH**
Add GCC 11 to the Ubuntu 18.04 Bionic and 20.04 Focal toolsets.

Closes #3280.

Please run `/azp run ubuntu1804, ubuntu2004` to test the images.

We probably should also start talking about a date to make GCC 11 the default.

------
### Check list
- [x] Related issue / work item is attached
- [x] Tests are written: By CI
- [x] Documentation is updated: By CI
- [x] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
> Builds pass!
> 
> > gfortran-11 ?
> 
> I don't think it's been packaged yet, I can't find it.

It is packaged, gcc-11 means all the gcc suite (C, C++, Fortran, Ada, Libraries ... )

Did you find g++-11 ?

**Comment by EwoutH** [comment]
Done, added GFortran 11 to the toolsets.

**Comment by AlenaSviridenko** [comment]
@EwoutH, please pull the latest main, it contains fix for Ruby gem installation for Ubuntu 20.04 (that is why it is failing)

**Comment by EwoutH** [comment]
Done!

**Review by miketimofeev — APPROVED** [review]

**Review by AlenaSviridenko — APPROVED** [review]

**Pull request merged**
