### PR TITLE
Update Install-NSIS.ps1

### PR DESCRIPTION
**Pull request by andrew-r-king**
Update NSIS to 3.08

See notes in #4739

# Description
New tool, Bug fixing, or Improvement?  
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.  
**For new tools, please provide total size and installation time.**

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by dmitry-shibanov — DISMISSED** [review]

**Comment by miketimofeev** [comment]
@andrew-r-king would you mind moving the version to the toolset file in the https://github.com/actions/virtual-environments/tree/main/images/win/toolsets folder?
Something like this would be fine
```
    "nsis": {
        "version": "3.08"
    },
```
And in the script you can get the version using our helper function:
`$nsisVersion = (Get-ToolsetContent).nsis.version`

This will allow us to avoid changes in the installation script next time when NSIS needs to be updated.

**Comment by andrew-r-king** [comment]
@miketimofeev Not a problem. See commit d564ca2. Let me know if anything else should be tweaked.

**Review by miketimofeev — APPROVED** [review]

**Review by al-cheb — APPROVED** [review]

**Pull request merged**
