### PR TITLE
Rework Mono installation to avoid using apt repos on Ubuntu images

### PR DESCRIPTION
**Pull request by dsame**
# Description
Improvement

Remove download.mono-project.com repo from the apt/sources.list

#### Related issues: https://github.com/actions/virtual-environments-internal/issues/2070
https://github.com/actions/virtual-environments/issues/2951#issuecomment-819658892

## Check list
- [x] Related issue / work item is attached
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by AlenaSviridenko** [comment]
Looks like not the whole string was pulled from the file
image

**Comment by AlenaSviridenko** [comment]
image
`main` is still missing

**Review by Albasha199 — COMMENTED** [review]
hgh

**Review by kitkat-create — COMMENTED** [review]
A Lil help?

**Review by kitkat-create — DISMISSED** [review]

**Review by miketimofeev — APPROVED** [review]

**Review by AlenaSviridenko — APPROVED** [review]

**Comment by dsame** [comment]
Changes will be available on the next roll out

**Pull request merged**
