### PR TITLE
Install clang-format

### PR DESCRIPTION
**Pull request by NilsIrl**
https://github.com/actions/virtual-environments/issues/104#issuecomment-589962007

### CODE REVIEW

**Comment by EFanZh** [comment]
How about making `clang-format-9` as the default `clang-format` using `update-alternatives`? Since `clang-9` and `clang++-9` has already been set as default.

**Comment by NilsIrl** [comment]
> How about making `clang-format-9` as the default `clang-format` using `update-alternatives`

Great idea! Pushed a commit for this.

**Comment by miketimofeev** [comment]
@NilsIrl I'm afraid you've missed the name for the clang-format
`update-alternatives: --install needs <link> <name> <path> <priority>`

**Comment by NilsIrl** [comment]
> I'm afraid you've missed the name for the clang-format

Thank you, fixed it.

**Pull request merged**
