### PR TITLE
compare php composer against latest signature

### PR DESCRIPTION
**Pull request by ropnop**
This addresses #146 

The SHA384 hash of the `composer-setup.php` script is hardcoded in the build script for the Ubuntu images. This means that whenever the install script is updated, the entire packer build fails and errors out on that step.

According to [this page from Composer](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md), the better way is to fetch the latest signature dynamically and compare it against the downloaded installer file.

I modified the php steps slightly to compare the hash against the latest official one from https://composer.github.io/installer.sig

Let me know if you think this is the best approach. The other approach would be to pin the installer to a specific hash and then downloading it by reference like `https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer`

### CODE REVIEW

**Comment by majorvin** [comment]
hey @ropnop  can you rebase your branch? 
@kaylangan i've tested the fix above, can we get someone to approve it after the rebase?

**Comment by ropnop** [comment]
Merged with upstream master

**Comment by ropnop** [comment]
I think the history is good now? Let me know, it got a little messy

**Comment by alepauly** [comment]
> 
> 
> I think the history is good now? Let me know, it got a little messy

@ropnop, something went wrong on that merge so I just went ahead and cherry-picked your commit unto a new clean branch and resubmitted as #194. I'll close this one and merge through that other one. Thanks again and sorry for the pain getting it merged :-)

**Pull request closed without merging**
