### PR TITLE
Update Haskell tool Stack

### PR DESCRIPTION
**Pull request by Ailrun**
# Description
Update the version of stack, as it fixes several issues related with haddock, Cabal 3, etc.

#### Related issue:
As far as I searched, there is no related issue.

## Check list
- [x] Related issue / work item is attached
- [N/A] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated
  I'm not on Windows, and I don't know how to use `ps1` under linux.

### CODE REVIEW

**Comment by miketimofeev** [comment]
Hi @Ailrun! 
Thanks for your contribution! 
Could you please remove changes in the Readme files? These docs are updated automatically.

**Comment by Ailrun** [comment]
Oops, I didn't know that. I will remove them.

**Comment by Ailrun** [comment]
Fixed

**Comment by miketimofeev** [comment]
Thanks!
By the way, what do you think about switching to install the latest version instead of specifying the exact one every time? It could be done by invoking `curl -sSL https://get.haskellstack.org/ | sh`

**Comment by Ailrun** [comment]
@miketimofeev I think that would be better, but how often GitHub Actions builds virtual env against the scripts?

**Comment by miketimofeev** [comment]
@Ailrun Usually, updates take place once a week if there are no delays due to found bugs

**Comment by Ailrun** [comment]
OK, that sounds reasonably short enough. I will update the script so that it installs stack using get.haskellstack.org

**Pull request merged**
