### PR TITLE
toolcache ruby 3.1

### PR DESCRIPTION
**Pull request by PatMyron**
`gsed -i 's/3\.0\.\*"/3.0.*",\n                "3.1.*"/' images/*/toolsets/*.json`

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by miketimofeev** [comment]
@PatMyron thanks for your contribution! I'm afraid we do not accept macOS contributions at the moment so could you please leave windows and ubuntu toolset updates only? We will take care of macOS ourselves

**Comment by PatMyron** [comment]
@miketimofeev done

**Review by al-cheb — APPROVED** [review]

**Review by miketimofeev — APPROVED** [review]

**Comment by miketimofeev** [comment]
@PatMyron thank you for your contribution! The new image will be deployed next week

**Pull request merged**
