### PR TITLE
refactor(windows): consistent file naming

### LINKED ISSUE #1636: Rename Windows Packer Configuration Files
**Description**  

Rename Windows Packer configuration files from `[OS][Release]-[Cloud].json` to `[OS][Release].json` and rely on the `builders` section to describe individual target platforms.

If necessary, `only` may be used at the `provisioner` level to restrict steps to specific target platforms.

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Feature?

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

### PR DESCRIPTION
**Pull request by hutson**
Use the same file naming scheme for Windows as is used for Ubuntu, where
the file name includes the Operating System name and release, but
not the target platform.

This also encourages downstream consumers to re-use the same files with
alternative targets by extending the `builders` section and using the
`-only` command line option with Packer to specify the build target.

Closes #1636

### CODE REVIEW

**Review by alepauly — APPROVED** [review]

**Comment by maxim-lobanov** [comment]
@hutson , sorry for delay.
Could you please update your PR and pull latest `main` changes to your branch?
We should also change 3 more files:
- https://github.com/actions/virtual-environments/blob/main/helpers/GenerateResourcesAndImage.ps1#L23
- https://github.com/actions/virtual-environments/blob/main/images.CI/linux-and-win/azure-pipelines/windows2016.yml#L19
- https://github.com/actions/virtual-environments/blob/main/images.CI/linux-and-win/azure-pipelines/windows2019.yml

**Comment by hutson** [comment]
I've updated the PR and made changes to the files suggested.

**Review by maxim-lobanov — APPROVED** [review]

**Review by AlenaSviridenko — APPROVED** [review]

**Review by al-cheb — APPROVED** [review]

**Pull request merged**
