### PR TITLE
Update docker compose to v1.25.4

### PR DESCRIPTION
**Pull request by nellyk**
This reopens this pr https://github.com/actions/virtual-environments/pull/149 raised by @beechtom and updates `docker-compose` to 1.25.4. Which provides features such as `--parallel`

### CODE REVIEW

**Comment by maxim-lobanov** [comment]
Hello @nellyk , thank you for contribution!

Could you please revert changes in files `images/linux/Ubuntu1604-README.md` and `images/linux/Ubuntu1804-README.md `? They are auto-generated and will be updated after next image rollout. No need to update them manually.

**Comment by nellyk** [comment]
Hi, @maxim-lobanov thank you for reviewing.
I've updated d6bcf00.

**Comment by JamesSingleton** [comment]
Can't wait for this to get it! Thanks for raising this PR!

**Comment by maxim-lobanov** [comment]
I have run CI builds, will merge PR as soon as they are green

**Pull request merged**
