### PR TITLE
[macOS] Upgrade Selenium server version from 3 to 4

### PR DESCRIPTION
**Pull request by dibir-magomedsaygitov**
# Description
We need to upgrade Selenium server version from 3 to 4.

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Comment by miketimofeev** [comment]
@dibir-magomedsaygitov does it make sense to create a test to make sure we are on version 4.* as we can't move selenium to toolset for macOS?

**Review by miketimofeev — APPROVED** [review]

**Review by al-cheb — APPROVED** [review]

**Review by MaksimZhukov — APPROVED** [review]

**Comment by nanish94** [comment]
https://github.com/actions/virtual-environments/pull/4474/commits/83ac5e0f6cbffc01a99b7dd6ac0724fccd3b06fb

**Pull request merged**
