### PR TITLE
Go 1.15

### PR DESCRIPTION
**Pull request by LKaemmerling**
# Description
Tool Update: go 1.15 was released yesterday and we at https://github.com/hetznercloud/hcloud-go want to test against go1.15

Actually i hope i got all relevant files, I'm not quite sure. I left the default to go1.14 (for now)

#### Related issue:
#1398 
## Check list
- [X] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by maxim-lobanov** [comment]
Thank you for contribution! Changes look good.
What do you think about updating default version to 1.15? Does it make sense to do it right now or later after a few patch versions 1.15.x

**Comment by LKaemmerling** [comment]
> Thank you for contribution! Changes look good.
> What do you think about updating default version to 1.15? Does it make sense to do it right now or later after a few patch versions 1.15.x

Actually i think it makes sense to do it after a few patch releases, but i don't know how the process was for go 1.14, maybe you have a bit more experience with that?

**Comment by maxim-lobanov** [comment]
> > Thank you for contribution! Changes look good.
> > What do you think about updating default version to 1.15? Does it make sense to do it right now or later after a few patch versions 1.15.x
> 
> Actually i think it makes sense to do it after a few patch releases, but i don't know how the process was for go 1.14, maybe you have a bit more experience with that?

Not much context but previously we have done it after a few patch releases.
Agree, let's keep 1.14 as default for now.

**Comment by maxim-lobanov** [comment]
@LKaemmerling , could you please pull the latest `main` to your branch? Looks like Windows builds failed with known issue  that should be already fixed.
Sorry for inconvenience.

**Comment by LKaemmerling** [comment]
@maxim-lobanov i rebased it from master 👍

**Comment by LKaemmerling** [comment]
@maxim-lobanov looks like they are still failing

**Comment by maxim-lobanov** [comment]
@LKaemmerling , sad :(
Stuck with one more Windows issue. PR with fix already submitted, will merge it soon: https://github.com/actions/virtual-environments/pull/1410

**Comment by dmitry-shibanov** [comment]
Hello, pull request with fix for windows was merged. Could you please update your pull request with new changes.

**Comment by LKaemmerling** [comment]
@maxim-lobanov @dmitry-shibanov i rebased my MR again, hopefully now everything works :)

**Comment by LKaemmerling** [comment]
Oh no @maxim-lobanov and again the Windows builds are failing 😰

**Comment by maxim-lobanov** [comment]
@LKaemmerling , we stuck with every possible bugs on Windows this week :) 
But finally images are green. Merging

**Pull request merged**
