### PR TITLE
Update oc CLI to OpenShift CLI

### PR DESCRIPTION
**Pull request by pcarney8**
# Description
New tool, Bug fixing, or Improvement?  

Documentation improvement. update oc CLI to OpenShift CLI (oc) similar to other CLIs in the Ubuntu image documentation

#### Related issue:
https://github.com/actions/virtual-environments/pull/2692

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by maxim-lobanov — APPROVED** [review]

**Review by miketimofeev — APPROVED** [review]

**Comment by imansameri** [comment]
> # Description
> New tool, Bug fixing, or Improvement?
> 
> Documentation improvement. update oc CLI to OpenShift CLI (oc) similar to other CLIs in the Ubuntu image documentation
> 
> #### Related issue:
> #2692
> 
> ## Check list
> * [ ]  Related issue / work item is attached
> * [ ]  Tests are written (if applicable)
> * [x]  Documentation is updated (if applicable)
> * [ ]  Changes are tested and related VM images are successfully generated

**Comment by imansameri** [comment]
Duplicate of #

**Comment by maxim-lobanov** [comment]
@pcarney8, thank you for contribution! I will merge PR.

**Pull request merged**
