### PR TITLE
Fix documentation for Windows images

### PR DESCRIPTION
**Pull request by vmapetr**
This PR related to the issue https://github.com/actions/virtual-environments/issues/310. It fixes Python topic in Windows InstalledSoftware.md and also fixes some minor issues.

**Details:**
Python 3.7.6 is set as default system Python for both Windows images.
Python 2.7 was removed from documentation because it is installed as Chocolately dependency.
Python and Ruby provisioners was merged with Toolcache provisioner.
Python and Ruby topics in documentation was moved to general toolcache topic 

**Example:**

## Python

_Version:_ 2.7.17 (x64)<br/>_Version:_ 3.5.4 (x64)<br/>_Version:_ 3.6.8 (x64)<br
/>_Version:_ 3.7.6 (x64)<br/>_Version:_ 3.8.2 (x64)<br/>_Version:_ 2.7.17 (x86)<br/>_Version:_ 3.5.4 (x86)<br/>_Version:_ 3.6.8 (x86)<br/>_Version:_ 3.7.6 (x86)<br/>_Version:_ 3.8.2 (x86)<br/><br/>__System default version:__ Python 3.7.6<br/>_Environment:_<br/>* Location: C:\hostedtoolcache\windows\Python\3.7.6\x64<br/>* PATH: contains the location of executable for Python 3.7.6<br/>

## PyPy

_Version:_ 2.7.13 (x86)<br/>_Version:_ 3.6.9 (x86)<br/>

## Ruby

_Version:_ 2.4.9 (x64)<br/>_Version:_ 2.5.7 (x64)<br/>_Version:_ 2.6.5 (x64)<br/>_Version:_ 2.7.0 (x64)<br/><br/>__System default version:__ Ruby 2.5.7p206<br/>_Environment:_<br/>* Location: C:\hostedtoolcache\windows\Ruby\2.5.7\x64\bin<br/>* PATH: contains the location of executable for Ruby 2.5.7p206<br/>* Gem Version: 2.7.6.2<br/>

### CODE REVIEW

**Comment by miketimofeev** [comment]
@vmapetr could you provide the readme sample with these changes, please?

**Comment by maxim-lobanov** [comment]
Could you please fix the pull-request title?

**Comment by vmapetr** [comment]
> @vmapetr could you provide the readme sample with these changes, please?

Done. Please check description.

**Comment by vmapetr** [comment]
> Could you please fix the pull-request title?

Done.

**Pull request merged**
