### PR TITLE
Update CMake to 3.17.0 on all environments

### PR DESCRIPTION
**Pull request by rick-de-water**
# Description
The newest version of CMake adds some nice new features, but is missing on the linux environments. I've simply updated the version number in the install script.

## Check list
- [x] Related issue / work item is attached
- [x] Documentation is updated
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by maxim-lobanov** [comment]
@rick-de-water , your first commit was the best one :)
We should not update documentation manually. We need to change only `images/linux/scripts/installers/cmake.sh`

**Comment by rick-de-water** [comment]
> @rick-de-water , your first commit was the best one :)
> We should not update documentation manually. We need to change only `images/linux/scripts/installers/cmake.sh`

Ah I see, I was wondering how you would keep that file up to date properly ^^

**Comment by rick-de-water** [comment]
I did a rollback, so it should just be the first commit now.

**Comment by maxim-lobanov** [comment]
> > @rick-de-water , your first commit was the best one :)
> > We should not update documentation manually. We need to change only `images/linux/scripts/installers/cmake.sh`
> 
> Ah I see, I was wondering how you would keep that file up to date properly ^^

It is updated automatically when the new image is deployed to all VMs.

**Pull request merged**
