### PR TITLE
Perform a full clone of vcpkg instead of depth=1

### PR DESCRIPTION
**Pull request by ras0219-msft**
# Description
The vcpkg versioning features rely on retrieving information from its git repository history. This means users need a deep clone to access earlier versions and baselines.

See https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#builtin-baseline for one of the user-facing points that requires specifying a git commit id from the history.

As a workaround until this is merged, users can run
```
git -C C:\vcpkg fetch --unshallow
```
(note that this command will fail once the repository is no longer shallow, so the exit code and error message should be ignored if possible)

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated
(All are N/A)

### CODE REVIEW

**Comment by miketimofeev** [comment]
Hi @ras0219-msft!
Could you please remove changes for macOS as we don't accept macOS contributions at the moment? We will create the PR for macOS ourselves.

**Comment by miketimofeev** [comment]
@ras0219-msft could you please pull the latest main to your branch and we will run the tests again?

**Comment by miketimofeev** [comment]
@ras0219-msft I'm going to close this PR. We can return to this once you updated the branch

**Comment by ras0219-msft** [comment]
I have pushed a merge from main

**Review by miketimofeev — APPROVED** [review]

**Comment by miketimofeev** [comment]
@ras0219-msft thank you for your contribution! The changes will be available next week.

**Pull request merged**
