### PR TITLE
using azure module in ps script, adjusted documentation

### LINKED ISSUE #1633: Missing requirements in instructions
**Description**  
For [GenerateResourcesAndImage.ps1](https://github.com/actions/virtual-environments/blob/main/helpers/GenerateResourcesAndImage.ps1) the `AzureRm` ps module is needed but that is not stated in the instructions.

**Expected behavior**  
I would like the documentation to be up to date and describing everything that has to be done.

**Note**
Is [this](https://github.com/actions/virtual-environments/blob/main/help/CreateImageAndAzureResources.md) the instruction one should refer to?
If my assumption with the incomplete requirements is correct, I would like to open a Pull request and correct the documentation.
I would just like to validate if I missed something.

Another potential fix would be to update the `GenerateResourcesAndImage.ps1` script to use the new `Azure` ps module or using the (already linked) `az` module that is already used in [CreateAzureVMFromPackerTemplate.ps1](https://github.com/actions/virtual-environments/blob/main/helpers/CreateAzureVMFromPackerTemplate.ps1).

### PR DESCRIPTION
**Pull request by zaanposni**
I hope you guys are merging into `main` and do not have another develop branch 🤔 ?

# Description

- Using new `Azure` ps module in `GenerateResourcesAndImage.ps1`.
- Updated the documentation to state that this module is required.

#### Related issue:

- #1633 

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [x] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by maxim-lobanov — APPROVED** [review]

**Comment by maxim-lobanov** [comment]
@zaanposni , LGTM! Thank you for contribution.
Did you have a chance to test it somehow?

**Review by AlenaSviridenko — APPROVED** [review]

**Comment by zaanposni** [comment]
Testing in form of executing and validating that the `Az` Calls are working? - I did that
But I did not write any softwaretests or similiar thats why I did not ticked that checkbox.

**Comment by maxim-lobanov** [comment]
> ating that the `Az` Calls are working? - I did that
> But I did not write any softwaretests or similiar thats why I did not ticked that checkbox.

Yes, if you run this script locally and it works well for you, it should work as testing here

**Review by alepauly — APPROVED** [review]
Thank you @zaanposni! this is great.

**Pull request merged**
