### PR TITLE
add az 3.5.0 to images

### PR DESCRIPTION
**Pull request by bgelens**
Add Az 3.5.0 Modules to ubuntu images

Solves #440

### CODE REVIEW

**Comment by al-cheb** [comment]
Hello, @bgelens 
Please don't update auto-generated documentation - Ubuntu1[68]04-README.md

**Comment by bgelens** [comment]
Fixed. Sorry about that

**Comment by maxim-lobanov** [comment]
Thank you for contribution!

**Comment by VOVELEE** [comment]
This is quite anticipated functionality :) Thanks @bgelens 

@maxim-lobanov , @sergey-akhalkov Do you have estimation when this will be implemented? Can we expect this in the beginning of March 2020?

**Comment by maxim-lobanov** [comment]
@VOVELEE , usually, it takes approximately 1 week for deployment so we can expect these changes at the begin of next week.

**Pull request merged**
