### PR TITLE
Enable Java tests since Java switching was fixed in MacOS 11.0

### PR DESCRIPTION
**Pull request by maxim-lobanov**
# Description
Switching Java was broken in MacOS 11.0 beta and Java tests were disabled previously.
Java was fixed in MacOS 11.0 beta 9 so enable test again.

Also enable Python 2 tests on Big Sur and return Python 2 to software report

## Check list
- [x] Tests are written (if applicable)
- [x] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by AlenaSviridenko — APPROVED** [review]

**Review by al-cheb — APPROVED** [review]

**Review by miketimofeev — APPROVED** [review]

**Comment by Smokes113** [comment]
abranjaramillo297@gmail.com

**Pull request merged**
