### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by aloviedo**
# Description
New tool, Bug fixing, or Improvement?  
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.  
**For new tools, please provide total size and installation time.**

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by miketimofeev — APPROVED** [review]

**Comment by miketimofeev** [comment]
@aloviedo is it possible to add the script to the exclusions? We don't use it during the image generation, it is needed only for VM provisioning process and we do not store any passwords in it
https://github.com/actions/virtual-environments/blob/main/images/macos/provision/bootstrap-provisioner/kcpassword.py

**Review by azboyzranch — APPROVED** [review]

**Comment by azboyzranch** [comment]
.>

**Comment by azboyzranch** [comment]
[Linter](https://github.com/actions/virtual-environments/actions/workflows/linter.yml)

**Comment by miketimofeev** [comment]
Closed in favour of https://github.com/actions/virtual-environments/pull/5411

**Pull request closed without merging**
