### PR TITLE
Add Clang 12 to Ubuntu 20.04 toolset

### PR DESCRIPTION
**Pull request by EwoutH**
### Description
Add Clang 12 to Ubuntu 20.04 toolset.

Installed size: 341.0 kB

### Virtual environments affected
- [x] Ubuntu 20.04

### Related issue
Does not apply

### Check list
- [x] Tests are written (if applicable)
- [x] Documentation is updated: Will be done by CI
- [x] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by Rada8732 — APPROVED** [review]

**Comment by AlenaSviridenko** [comment]
Hi @EwoutH,
look like clang-12 is not available for Ubuntu 20.04. Installation fails with `E: Unable to locate package clang-12`, and `apt-cache search clang-12` returns nothing for Ubuntu 20.04

**Comment by EwoutH** [comment]
You're right, it's [available](https://packages.debian.org/sid/clang-12) on Debian sid but [not](https://packages.ubuntu.com/focal-updates/clang-12) on Ubuntu focal-updates yet, I see now.

**Review by SonjayaJetBrain — APPROVED** [review]

**Comment by EwoutH** [comment]
I think this might work, could you run again?

**Comment by EwoutH** [comment]
Looks likes it passes!

When Clang 12 is available on [focal-updates](https://packages.ubuntu.com/focal-updates/clang-12) we can revert that second commit and switch back.

**Comment by AlenaSviridenko** [comment]
Hi @EwoutH,
If you don't mind, we are going to merge your PR closer to the Clang 9 removal date (announcement issue https://github.com/actions/virtual-environments/issues/3235).
Thank you for contribution!

**Comment by EwoutH** [comment]
Maybe we could merge Clang 12 this week, that would allow to migrate to GGC 11 and Clang 12 simultaneously.

**Review by miketimofeev — APPROVED** [review]

**Comment by AlenaSviridenko** [comment]
@EwoutH, Clang 12 takes about 600Mb of space, and we have to be very careful in installing big tools on Ubuntu images due to space issues we had previously. So I'd prefer to wait until the Clang 9 removal date and add Clang 12 only then.

**Review by AlenaSviridenko — APPROVED** [review]

**Pull request merged**
