### PR TITLE
[windows] Add Terraform tool

### PR DESCRIPTION
**Pull request by sujithq**
# Description
Added Terraform tool to the Windows versions similar like Linux versions

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by maxim-lobanov** [comment]
@sujithq , have you tried [official terraform action](https://github.com/marketplace/actions/hashicorp-setup-terraform)?
According to GitHub Actions documentation, it is recommended way: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#using-preinstalled-software

**Comment by sujithq** [comment]
> @sujithq , have you tried [official terraform action](https://github.com/marketplace/actions/hashicorp-setup-terraform)?
> According to GitHub Actions documentation, it is recommended way: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#using-preinstalled-software

I am just referring to the contributing readme, bullet point 2 because it is installed on the Linux versions.

I agree with your first link if you use GitHub actions and for Azure DevOps we could use https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform.

Consider this situation: you are only allowed to use self-hosted agents for Azure DevOps and those agents are locked down from the internet. You have to use the existing toolset.  Combine this with the normal use of the actions for GitHub and Azure DevOps (pin the version of Terraform with the version installed by default you are ready to go.)

Our current self-hosted agents have a smaller toolset. We are going to use this repository as a starting point (make them compliant ex CIS) to build richer agents for a broader use.

**Comment by AlenaSviridenko** [comment]
Hi @sujithq,
for self-hosted images that are built based on our fork, usually all extra tools and other customization are added to the fork. We wouldn't like to add this tool to the image, because for GitHub-hosted images, there is an official action. And we are also trying to avoid installing new tools now unless it is critical and more focused on stabilizing current images.

**Comment by sujithq** [comment]
> Hi @sujithq,
> for self-hosted images that are built based on our fork, usually all extra tools and other customization are added to the fork. We wouldn't like to add this tool to the image, because for GitHub-hosted images, there is an official action. And we are also trying to avoid installing new tools now unless it is critical and more focused on stabilizing current images.

Thank you for your explanation. Does this mean that there is more focus on GitHub-Hosted images and less on Azure Devops hosted although this source is used for both? Is there a chance that support stops for Azure Devops?

**Comment by AlenaSviridenko** [comment]
Actually, no, Azure DevOps support is not dropped, this repo fits for both types of issues: GitHub Actions and Azure DevOps, as it contains the code for the images that are deployed to both services.
My point was that for self-hosted images, the recommended way to customize them is to modify the personal fork of our repository. 
This repository is intended for hosted images, so [we are considering a lot of things](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-preinstallation-policy) when deciding whether to add or not something on hosted images, because it can affect other customers.

**Comment by sujithq** [comment]
> Actually, no, Azure DevOps support is not dropped, this repo fits for both types of issues: GitHub Actions and Azure DevOps, as it contains the code for the images that are deployed to both services.
> My point was that for self-hosted images, the recommended way to customize them is to modify the personal fork of our repository.
> This repository is intended for hosted images, so [we are considering a lot of things](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-preinstallation-policy) when deciding whether to add or not something on hosted images, because it can affect other customers.

One more thing. Why is Terraform pre-installed on Ubuntu 18.04 and Ubuntu 20.04? Shouldn't Terraform being removed as there is a recommended way?

**Comment by AlenaSviridenko** [comment]
Well, removing something that already exists on the image is a big deal, we cannot predict the amount of customers who use that pre-installed terraform (or any other tool) and we have to be very careful when removing it. 
We defined clear guidelines not so long ago, so there are tools that might not match that guidelines, but for the sake of saving stable customers' workflow we cannot remove them for now.

**Comment by sujithq** [comment]
> Well, removing something that already exists on the image is a big deal, we cannot predict the amount of customers who use that pre-installed terraform (or any other tool) and we have to be very careful when removing it.
> We defined clear guidelines not so long ago, so there are tools that might not match that guidelines, but for the sake of saving stable customers' workflow we cannot remove them for now.

Ok. I will close my PR.

**Pull request closed without merging**
