### PR TITLE
[Windows] bind openssl.light version to 1.1.1.x

### PR DESCRIPTION
**Pull request by mikhailkoliada**
# Description
This commit binds the openssl.light version to 1.1.1.x, otherwise we are installing the 3.0.0 version which was released on September 7th lacking any backward compatibility and adding lots of new features potentially causing breakages in the existing software.

## Check list
- [X] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Comment by al-cheb** [comment]
nitpick: I think we should add a small test to check openssl version and failed the build if it bumps unexpectedly.

**Review by dibir-magomedsaygitov — APPROVED** [review]

**Review by miketimofeev — APPROVED** [review]

**Review by MaksimZhukov — APPROVED** [review]

**Review by dmitry-shibanov — APPROVED** [review]

**Review by vsafonkin — APPROVED** [review]

**Pull request merged**
