### PR TITLE
Upgrade to Az 3.8

### PR DESCRIPTION
**Pull request by bergmeister**
# Description
New tool, Bug fixing, or Improvement?  
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.  
**For new tools, please provide total size and installation time.**

This new version contains a few new commands that 3.5.0 does not have: https://www.powershellgallery.com/packages/Az/3.8.0

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Comment by al-cheb** [comment]
Hello, @bergmeister 
Could you please update https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Validate-AzureModules.ps1 script to add the new version Az 3.8.0?

**Comment by bergmeister** [comment]
@al-cheb Sure, done now. As far as I see, your build process will update the Readme files, like e.g. this one [here](https://github.com/actions/virtual-environments/blob/patch-1/images/win/Windows2016-Readme.md), is that correct?

**Comment by al-cheb** [comment]
@bergmeister, You are right. This is auto-generated documentation and we don't need to update it manually.

**Comment by maxim-lobanov** [comment]
Thank you for contribution. CI is green and I have merged PR. Changes will be propagated to all VMs in 1 week.

**Comment by bergmeister** [comment]
Thanks, amazing work from your side as well for the quick review and pushing it out that quickly. :-)
I've tweeted about my positive experience and evens GitHub's CEO seems to like it: https://twitter.com/CBergmeister/status/1255152458415763462

**Pull request merged**
