### PR TITLE
added -notmatch "kind-windows-amd64.sha256sum"

### PR DESCRIPTION
**Pull request by adityajalkhare**
added -notmatch "kind-windows-amd64.sha256sum"  to kindDownloadLink assignment command

# Description
New tool, Bug fixing, or Improvement?  
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.  
**For new tools, please provide total size and installation time.**

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by Shutch748 — CHANGES_REQUESTED** [review]
Shutch:master

**Review by Shutch748 — CHANGES_REQUESTED** [review]
images/win/scripts/Installers/Install-KubernetesTools.ps1

**Comment by miketimofeev** [comment]
@adityajalkhare could you get this PR out of draft so we can test it and merge if everything is ok?

**Comment by panekj** [comment]
@miketimofeev this seems to be already fixed in https://github.com/actions/virtual-environments/pull/5217

**Comment by adityajalkhare** [comment]
@miketimofeev, I was about to publish it then saw someone else had submitted and merged changes. Hence closing the PR.
Thanks :)

**Pull request closed without merging**
