### PR TITLE
[macOS] Add Xcode 12.2 & 12.3 beta

### PR DESCRIPTION
**Pull request by miketimofeev**
# Description
New Xcode versions were released and also Big Sur doesn't need a beta version of command line tools anymore.

#### Related issue:
n\a

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

### CODE REVIEW

**Review by al-cheb — APPROVED** [review]

**Review by dibir-magomedsaygitov — APPROVED** [review]

**Review by maxim-lobanov — APPROVED** [review]

**Review by AlenaSviridenko — APPROVED** [review]

**Review by AlenaSviridenko — APPROVED** [review]

**Comment by Shchvova** [comment]
Hey folks. Is there any way to see when & if images has been deployed to GitHub action runners?
Thanks!

**Comment by maxim-lobanov** [comment]
@Shchvova , It will be deployed during this week.

**Comment by Shchvova** [comment]
@maxim-lobanov thanks so much! Waiting for it with anticipation, since apple asks to upload Apple Silicon binaries now.

**Comment by maxim-lobanov** [comment]
@Shchvova , Images already contains Xcode 12.2 RC and it allows to submit binaries to AppStore. Just a temporary workaround

**Pull request merged**
